FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy only the Chatbot folder content into /app
COPY Chatbot/ /app

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose the port used by Streamlit
EXPOSE 8501

# Run Streamlit application
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]


